# Generated by Django 3.1.2 on 2024-07-02 17:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_estadoenvio_estadomodificacion_estadoorden'),
    ]

    operations = [
        migrations.AddField(
            model_name='factura',
            name='estadoEnvio',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estadoenvio'),
        ),
        migrations.AddField(
            model_name='factura',
            name='estadoModificacion',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estadomodificacion'),
        ),
        migrations.AddField(
            model_name='factura',
            name='estadoOrden',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.estadoorden'),
        ),
    ]
