# Generated by Django 3.1.2 on 2024-07-03 05:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20240702_1335'),
    ]

    operations = [
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direccion', models.CharField(max_length=200)),
                ('rut', models.CharField(max_length=15)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='entregas/')),
            ],
        ),
        migrations.CreateModel(
            name='Rechazo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.TextField()),
                ('factura', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.factura')),
            ],
        ),
        migrations.AddField(
            model_name='factura',
            name='entrega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.entrega'),
        ),
    ]
