# Generated by Django 3.1.2 on 2024-07-04 04:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20240703_0118'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entrega',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='factura',
            name='entrega',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.entrega'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estadoEnvio',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estadoenvio'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estadoModificacion',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estadomodificacion'),
        ),
        migrations.AlterField(
            model_name='factura',
            name='estadoOrden',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.estadoorden'),
        ),
    ]
